# Generated by Django 5.1.1 on 2024-10-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
